#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class TextBlock;
                ref class TextBox;
                ref class Button;
            }
        }
    }
}

namespace WorQUWP
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::VisualState^ wideState;
        private: ::Windows::UI::Xaml::VisualState^ narrowState;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ contentPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ inputPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ entryReceived;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ queueTable;
        private: ::Windows::UI::Xaml::Controls::TextBox^ pinSignOut;
        private: ::Windows::UI::Xaml::Controls::Button^ signOutButton;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ firstInLine;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ secInLine;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ thirdInLine;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ fourthInLine;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ fifthInLine;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ fifthName;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ fifthTime;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ fourthName;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ fourthTime;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ thirdName;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ thirdTime;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ secName;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ secTime;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ firstName;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ firstTime;
        private: ::Windows::UI::Xaml::Controls::TextBox^ nameInput;
        private: ::Windows::UI::Xaml::Controls::TextBox^ emailInput;
        private: ::Windows::UI::Xaml::Controls::TextBox^ pinInput;
        private: ::Windows::UI::Xaml::Controls::Button^ inputButton;
    };
}

